version: '3.7'

services:
  app:
    build: .
    volumes:
      - "code:/var/www/app"
    depends_on:
      - db
  web:
    image: nginx:latest
    volumes:
      - "./docker/web/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "code:/var/www/app:ro"
    depends_on:
      - app
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=appuser
    volumes:
      - "mysqldata:/var/lib/mysql"

volumes:
  code:
  mysqldata:
