##
# Template for production
##
version: '3.7'

services:
  app:
    environment:
      - APP_ENV=prod
      - MYSQL_HOST=db
      - MYSQL_DATABASE=app
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  web:
    ports:
      - "80:80"
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
