##
# Template for development
##
version: '3.7'

services:
  app:
    build:
      target: dev
    hostname: app
    environment:
      - XDEBUG_CONFIG=remote_enable=1 remote_host=host.docker.internal
      # - PHP_IDE_CONFIG=serverName=php-docker-app
      - MYSQL_HOST=db
      - MYSQL_DATABASE=app
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  web:
    hostname: web
    ports:
      - "80:80"
  db:
    hostname: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
    ports:
      - "8080:80"

volumes:
  code:
    driver: local

    # Connects to the docker host via nfs;
    # works with cifs on windows and local mapping on linux, as well;
    # adust to your needs.
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PROJECT_DIR}}"
